eureka:
  client:
    serviceUrl:
      #      eureka的注册中心地址
      defaultZone: http://localhost:8888/eureka/
  #服务端要多次启动，所以使用输入port的模式
#server:
#  此项目端口号
#  port: 8886
spring:
  application:
    #    注册进eureka的名字
    name: provider-server
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springcloud?useSSL=false&?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 2
mybatis:
  # 注意：一定要对应mapper映射xml文件的所在路径
  mapper-locations: classpath:mapping/*.xml
  # 注意：对应实体类的路径
  type-aliases-package: com.dr.model
